### ISSUE TITLE
Etag exists in cloud but not in local copy

### ISSUE THREAD

**Issue by FPMilan** [keisentraut/awsbackup#1]
Hi @keisentraut 
thank you for this script! 
When trying it out I am getting the above error, can you assist me in how to resolve this?
The file gets uploaded and an etag is also created locally but not a matching one.
Thanks in advance
Milan

**Comment by keisentraut** [comment]
This error can occur because of two reasons:

1. You have manually deleted a file from your disk but you didn't remove it from cloud and/or the ETAGS.txt/SHA256.txt files. 
2. The AWS Etag is just an MD5 of the multipart chunks. If you have changed the multipart chunksize in e.g. ```~/.aws/config``` then you will need to set the same value in the script too. Otherwise the ETAG will not match with the locally calculated one. See [this StackOverflow](https://stackoverflow.com/a/19896823) answer for more details.

I think it will be issue 2 because you explicitly stated that
>  The file gets uploaded and an etag is also created locally but not a matching one.

**Comment by FPMilan** [comment]
Thanks for your answer! 
Did a little investigation and I think the error is a sub case of 1.
I deleted a file everywhere but apparently it still gets recognized by AWS cli as to be in my cloud bucket. Maybe that just takes a while until it disappears.
